import { test, expect } from "@playwright/test";
test('test', async ({ page }) => {
  await page.goto('https://192.168.1.33:4442/');
  await page.getByPlaceholder('Enter username').click();
  await page.getByPlaceholder('Enter username').fill('Admin');
  await page.getByPlaceholder('Enter password').click();
  await page.getByPlaceholder('Enter password').fill('Admin@123');
  //await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Login' }).click();
  //await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Server Configuration' }).click({timeout: 20000});
  await page.getByRole('button', { name: 'Create Server' }).click();
  await page.getByPlaceholder('Enter server name').click();
  await page.getByPlaceholder('Enter server name').fill('Test_Server_01');
  await page.getByPlaceholder('Enter server port').click();
  await page.getByPlaceholder('Enter server port').fill('443');
  await page.getByPlaceholder('Enter UTC Offset').click();
  await page.getByPlaceholder('Enter UTC Offset').fill('-07:00:00');
  await page.getByPlaceholder('Choose an Environment...').click();
  await page.locator("//a[@id='envId-item-7']").click();
  await page.getByPlaceholder('Choose a Domain...').click();
  await page.locator("//a[@id='domainId-item-4']").click();
  await page.getByPlaceholder('Choose an app...').click();
  await page.locator("//a[@id='appId-item-0']").click();
  await page.locator("//button[@id='add-app-btn']").click();
 // await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Submit' }).click();
  //await page.waitForTimeout(5000);
  await page.getByRole('button', { name: 'View Servers' }).click();
  await page.getByPlaceholder('Choose a server...').click();
  //await page.waitForTimeout(2000);
  await page.getByPlaceholder('Choose a server...').fill('New');
 // await page.waitForTimeout(2000);
  await page.locator("//a[@id='serverTypeahead-item-3']").click();
  //await page.waitForTimeout(2000);
  await page.getByPlaceholder('Enter server port').click();
  await page.getByPlaceholder('Enter server port').fill('4433');
  await page.getByPlaceholder('Choose a Environment...').click();
  //await page.waitForTimeout(1000);
  await page.getByPlaceholder('Choose a Environment...').fill('UAT');
  //await page.waitForTimeout(2000);
  await page.locator("//a[@id='envId-item-0']").click();
  //await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('button', { name: 'View Servers' }).click();
  await page.getByPlaceholder('Choose a server...').click();
  await page.getByPlaceholder('Choose a server...').fill('New');
 // await page.waitForTimeout(2000);
  await page.locator("//a[@id='serverTypeahead-item-3']").click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Delete Server' }).click();
  await page.getByRole('button', { name: 'Yes' }).click({timeout: 10000});
  //await page.waitForTimeout(2000);
 
});